watercrawl/WaterCrawl

- README.md
- Add status badges (GitHub, Docker, License)
- Add emojis to all sections
- Improve overall formatting and layout
- Fix typos and broken links
- Add footer with team attribution
> docs: enhance README with badges and emojis 🎨

- backend/common/docs.py
fix: use gettext instead of gettext_lazy to fix error
> fix: use gettext instead of gettext_lazy to fix error

- docs/package.json
- docs/pnpm-lock.yaml
fix: update redoc package to use latest version
> fix: update redoc package to use latest version

- CONTRIBUTING.md
- Fix copy command for .env.local file
- Add poetry prefix to ruff commands
- Remove redundant Docker development section
- Clarify that development can begin immediately after issue creation
-  [x] Documentation update
> docs: update CONTRIBUTING.md with correct file paths and commands

- DEPLOYMENT.md
- README.md
- docker/.env.example
- docker/.env.local
- docker/docker-compose.yml
- docker/nginx/entrypoint.sh
- docker/nginx/nginx.conf
- Replace static Nginx config with template-based dynamic configuration
- Add Nginx entrypoint script to substitute environment variables
- Add support for MinIO private and public bucket routing
- Update environment files with domain configuration examples
- Add warnings in documentation about MinIO endpoint configuration
- Improve file upload/download functionality through Nginx proxy
This change enables proper file handling when deployed to custom domains by ensuring correct URL generation for stored files.
> feat(docker): implement dynamic Nginx configuration for MinIO buckets

- frontend/src/components/activity-logs/ActivityLogResultCard.tsx
- frontend/src/components/sitemap/SitemapGraphViewer.tsx
- frontend/src/types/crawl.ts
> fix: fix build issue

- .github/workflows/manual-version-bump.yml
- Introduce manual-version-bump.yml for workflow_dispatch version bumps
- Automates branch creation, multi-file version update, commit, push, and PR to main
- Ensures all version strings in DEPLOYMENT.md, .env.example, pyproject.toml, and docker-compose.yml are updated consistently for each release
> ci(github): add manual version bump and release PR workflow

- .github/workflows/docker-publish.yml
> chore: minor fixes

- docs/pnpm-lock.yaml
- frontend/package.json
- frontend/pnpm-lock.yaml
> security: fix audit issues

- DEPLOYMENT.md
- backend/pyproject.toml
- docker/.env.example
- docker/docker-compose.yml
- frontend/src/contexts/SettingsProvider.tsx
> Release v0.6.0

- tutorials/FLARE-WaterCrawl-LangChain.ipynb
> flare, langchain, watercrawl tutorial added

- tutorials/Claude-3.7-WaterCrawl-stock-analyzer/Claude-3.7-&-WaterCrawl-stock-analyzer.py
- tutorials/Claude-3.7-WaterCrawl-stock-analyzer/Stock_Analyzer_Claude-3.7_WaterCrawl.ipynb
Stock analysis tutorial leveraging Claude sonnet 3.7 was added
> stock analysis tutorial

- backend/common/serializers.py
- backend/common/services.py
- backend/core/serializers.py
- backend/core/services.py
- backend/core/views.py
- backend/spider/settings.py
- backend/spider/spiders/google_search.py
- backend/watercrawl/settings.py
- frontend/src/contexts/SettingsProvider.tsx
- frontend/src/layouts/DashboardLayout.tsx
- frontend/src/pages/dashboard/SearchPage.tsx
- frontend/src/types/settings.ts
- Replace HTML scraping with official Google Custom Search API
- Add configuration instructions in the search UI when not set up
- Update settings provider and related components
- Add environment variables for Google API credentials
Related #44
> feat(search): replace scraping with Google Custom Search API

- DEPLOYMENT.md
- backend/pyproject.toml
- docker/.env.example
- docker/docker-compose.yml
* flare, langchain, watercrawl tutorial added by @alexmofidi in https://github.com/watercrawl/WaterCrawl/pull/36
* stock analysis tutorial by @alexmofidi in https://github.com/watercrawl/WaterCrawl/pull/37
* feat: Add search functionality to WaterCrawl by @amirasaran in https://github.com/watercrawl/WaterCrawl/pull/47
* feat(search): replace scraping with Google Custom Search API by @amirasaran in https://github.com/watercrawl/WaterCrawl/pull/48
* feat(search): replace scraping with Google Custom Search API by @amirasaran in https://github.com/watercrawl/WaterCrawl/pull/49
* fix: add missing envs by @amirasaran in https://github.com/watercrawl/WaterCrawl/pull/50
* @alexmofidi made their first contribution in https://github.com/watercrawl/WaterCrawl/pull/36
> chore(release): bump version to v0.7.0

- CHANGELOG.md
- backend/plan/services.py
- backend/plan/validators.py
- frontend/src/components/search/SearchForm.tsx
- frontend/src/pages/dashboard/SearchPage.tsx
- Fix search credit calculation to properly account for search depth
- Add daily credit limit validation with improved error messages
- Enhance error handling in frontend with detailed backend error messages
- Add beta tag to Search Playground title
- Rename API tab to API Documentation for better clarity
This hotfix addresses issues with credit calculation for search operations and improves the user experience with more descriptive error messages.
> fix(search): credit calculation and validation

- docs/docs/api/cancel-search.md
- docs/docs/api/create-search.md
- docs/docs/api/get-search.md
- docs/docs/api/monitor-search.md
- docs/docs/api/overview.md
- docs/docs/clients/go.md
- docs/docs/clients/nodejs.md
- docs/docs/clients/php.md
- docs/docs/clients/python.md
- docs/docs/self-hosted/configuration.md
- docs/docs/self-hosted/installation.md
- docs/docs/self-hosted/overview.md
- docs/docs/self-hosted/services.md
- docs/docs/self-hosted/troubleshooting.md
- docs/sidebars.ts
- Add documentation for creating search requests
- Add documentation for monitoring search status with SSE
- Add documentation for retrieving search request details
- Add documentation for cancelling ongoing searches
- Update sidebar navigation to include search API endpoints
- Update related client and self-hosted documentation
Resolve https://github.com/watercrawl/WaterCrawl/issues/43
> docs(api): add comprehensive search API documentation

- backend/poetry.lock
- backend/pyproject.toml
feat: upgrade outdated dependencies
> feat: upgrade outdated dependencies

- CHANGELOG.md
- DEPLOYMENT.md
- backend/pyproject.toml
- docker/.env.example
- docker/backend/Dockerfile
- docker/docker-compose.yml
bump version to v0.8.0
- Proxy server management with UI for configuration and testing
- Comprehensive API documentation for search functionality
- New tutorials for R1 integration and webpage chat
- Support for backend plugins via Docker
- Docker configuration for better plugin support and version management
- Improved UI loading states with skeleton components
- Enhanced error pages with troubleshooting information
- Resolved Playwright configuration issues
- Fixed dependency conflicts and cleaned up codebase
- Improved error handling and user feedback
- Upgraded outdated packages for security and performance
- Added dependencies for proxy management
> chore(release): bump version to v0.8.0

- backend/core/views.py
fix: update perform_destroy method to handle SearchRequest and change summary to 'Stop search request'.
The current api used crawlerservice instead of searchservice
> fix: update perform_destroy method to handle for search request api view

- docs/package.json
- docs/pnpm-lock.yaml
- frontend/package.json
- frontend/pnpm-lock.yaml
Update package dependencies and overrides for compatibility
N/A
N/A
N/A
___
Bug fix
___
- Add security overrides for vulnerable packages
- Update webpack-dev-server to version 5.2.2
- Upgrade various dependencies for compatibility
- Add pnpm overrides for form-data and ESLint plugin-kit
___
```mermaid
flowchart LR
A["Security Vulnerabilities"] --> B["Package Overrides"]
B --> C["webpack-dev-server@5.2.2"]
B --> D["on-headers@>=1.1.0"]
B --> E["form-data@>=4.0.4"]
B --> F["@eslint/plugin-kit@>=0.3.4"]
C --> G["Updated Dependencies"]
D --> G
E --> G
F --> G
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Security</strong></td><td><table>
<tr>
<td>
<details> …
> chore: update package dependencies and overrides for compatibility

- CHANGELOG.md
- DEPLOYMENT.md
- backend/pyproject.toml
- docker/.env.example
- docker/backend/Dockerfile
- docker/docker-compose.yml
- docs/docs/self-hosted/configuration.md
- docs/docs/self-hosted/services.md
- **Configurable concurrent requests setting for crawls** - Added support for custom concurrency limits per crawl request
- Backend: New `concurrent_requests` field in crawl serializers and services
- Introduced `LimitRequestsMiddleware` to enforce per-crawl request limits
- Exposed `max_crawl_concurrency` via settings API
- Frontend: Added "Concurrent Requests" field to SpiderOptions form with dynamic max value from settings
- Updated all API documentation and client examples
- **Ignore rendering option** - Added ability to skip JavaScript rendering for faster crawls
- New `ignore_rendering` field to bypass Playwright rendering when JavaScript execution is not needed
- Consistent handling across crawl and sitemap spiders
- UI toggle in PageOptions form for easy control
- **Storage …
> Release v0.10.0

- backend/core/services.py
- backend/spider/spiders/sitemap.py
fix: enhance sitemap handling with max requests limit and nested sitemap detection
N/A
N/A
___
Bug fix, Enhancement
___
- Add error handling for sitemap crawling subprocess failures
- Implement max requests limit configuration for sitemap crawler
- Enhance nested sitemap detection for XML files
- Improve gzipped content detection logic
___
```mermaid
flowchart LR
A["Sitemap Service"] --> B["Error Handling"]
A --> C["Subprocess Execution"]
B --> D["Status Update"]
E["Sitemap Spider"] --> F["Max Requests Limit"]
E --> G["Nested Sitemap Detection"]
G --> H["XML File Detection"]
E --> I["Gzip Content Handling"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Error …
> fix: enhance sitemap handling with max requests limit and nested sitemap detection

- DEPLOYMENT.md
- backend/pyproject.toml
- docker/.env.example
- docker/backend/Dockerfile
- docker/docker-compose.yml
- docs/docs/self-hosted/configuration.md
- docs/docs/self-hosted/services.md
fix: enhance sitemap handling with max requests limit and nested sitemap detection
___
Other
___
- Bump application version from v0.10.0 to v0.10.1
- Update version references across deployment files
- Synchronize Docker configurations with new release
___
```mermaid
flowchart LR
A["Version Update"] --> B["DEPLOYMENT.md"]
A --> C["pyproject.toml"]
A --> D[".env.example"]
A --> E["Dockerfile"]
A --> F["docker-compose.yml"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>DEPLOYMENT.md</strong><dd><code>Update version documentation to v0.10.1</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Release v0.10.1

- backend/spider/spiders/sitemap.py
add path validation to sitemap handling for allowed URLs
N/!
N/A
___
Bug fix
___
- Add path validation to sitemap URL processing
- Prevent inclusion of URLs outside allowed paths
- Enhance URL filtering with `is_allowed_path` check
___
```mermaid
flowchart LR
A["URL from sitemap"] --> B["Domain validation"]
B --> C["Path validation"]
C --> D["Search query validation"]
D --> E["Append to results"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>sitemap.py</strong><dd><code>Add path validation to URL filtering</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix: add path validation to sitemap handling for allowed URLs

- backend/core/services.py
feat: implement BM25 scoring for URL path relevance in sitemap search filtering
N/A
N/A
___
Enhancement
___
- Replace boolean search filtering with BM25 scoring algorithm
- Add configurable relevance threshold for URL path matching
- Implement tokenization and term frequency analysis for paths
- Enhance search precision with weighted scoring system
___
```mermaid
flowchart LR
A["Search Query"] --> B["Tokenize Path"]
B --> C["Calculate Term Frequency"]
C --> D["Apply BM25 Formula"]
D --> E["Score vs Threshold"]
E --> F["Filter Results"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details> …
> feat: implement BM25 scoring for URL path relevance in sitemap search filtering

- docker/backend/Dockerfile
- docker/backend/extra_requirements.txt
- docker/docker-compose.yml
- docker/nginx/nginx.conf
- Docker backend:
- Add support for VERSION build ARG in backend Dockerfile.
- Update watercrawl-openai dependency to v0.1.1 in extra_requirements.txt. (Now supports new models and openai library updated)
- Docker Compose:
- Correct backend build context to "backend/" and pass VERSION arg for image versioning.
- Fix MCP service to connect to app on port 9000.
- Nginx:
- Refine location regex for SSE/messages endpoints.
- Add proxy settings required for efficient SSE (disable buffering, extend timeouts, use HTTP/1.1).
N/A
N/A
N/A
___
Bug fix, Enhancement
___
- Fix Docker configuration and service connectivity issues
- Update watercrawl-openai dependency to v0.1.1
- Enhance nginx proxy settings for SSE streaming
- Correct build contexts and service ports
___
```mermaid
flowchart LR …
```
> fix: Improve Docker and reverse proxy configuration

- CHANGELOG.md
- DEPLOYMENT.md
- backend/pyproject.toml
- docker/.env.example
- docker/backend/Dockerfile
- docker/docker-compose.yml
- docs/docs/self-hosted/configuration.md
- docs/docs/self-hosted/services.md
- **API Reference Page** - New comprehensive API reference page with dynamic theming and schema display
- **MCP Server** - Added MCP server
- **MCP Integration** - Added MCPServerAccess component to facilitate access to MCP (Model Context Protocol) features
- **Subscription Management** - PlansDisplay and PlansModal components for improved subscription management
- **BM25 Search Scoring** - Implemented BM25 scoring for URL path relevance in sitemap search filtering with URL decoding support
- **Dashboard Redesign** - Completely revamped dashboard layout with new welcome header, QuickNavigation, and ResourcesShortcuts sections
- **Improved User Experience** - Enhanced overall user onboarding experience and access to new platform capabilities
- **Responsive Design** - Made DashboardPage …
> Release v0.10.2
